### ISSUE TITLE
Import *.robot which has special character (thai characters) then rfmanager display error

### ISSUE THREAD

**Issue by castiny** [damies13/rfswarm#97] opened 2021-11-05 06:57 UTC
**Describe the bug**
In tab Plan, I was created plan by input robot, Delay, Ramp Up, Run, Script and Test. When I selected *.robot file which has special characters (thai characters) then at command prompt display error " .... return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2207: character maps to <undefined>"

**To Reproduce**
1. Go to tab Plan
2. Input Robots, Delay, Ramp up, Run then select script file in Script
3. See error as shown in screenshots (Error at command prompt)

**Expected behavior**
rfswarn should not display error and displayed all testname in test dropdown

**Screenshots**
- Error at command prompt
![image](https://user-images.githubusercontent.com/4536596/140469503-f78f4dca-8564-4289-91ae-a3266f65a19f.png)

- Example *.robot which has special characters (thai character)
![image](https://user-images.githubusercontent.com/4536596/140469854-09abde2f-957d-45e2-bc7e-6729eebc89c9.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome Browser 95.0.4638.69
 - Robot Framework 4.1.2
 - rfswarm manager 0.81

Best regards,
W. Leelapatra

**Comment by damies13** [comment] 2021-11-08 01:52
Hi, Thanks for the report, that's quite interesting as I would not have expected rfswarm to even care about that row, the only thing it needs from the test case section is the test case names.

I will investigate further when I get a chance. can you include the text in a comment, so I can put it in a test case an reproduce the issue.

Dave.

**Comment by castiny** [comment] 2021-11-20 14:29
I' m sorry to answer late. These are text in a comment show as below:
1. ข้าเป็นสัตว์เลี้ยงของศาลต้าหลี่ เล่ม 2
2. สองนครสิบห้าวัน เล่ม 2

Best regards,
W. Leelapatra

**Comment by damies13** [comment] 2021-11-25 12:21
The first step in figuring out how to fix this is gathering information to reproduce it, can you confirm which python version you are using?

I created the following robot file, this works for me so I would like to know if it also gives you the same error?

LanguageTests.robot:
```
*** Settings ***

*** Variables ***
${thai_variable} 	ข้าเป็นสัตว์เลี้ยงของศาลต้าหลี่

*** Test Cases ***
Thai Test 1
	Log 	ข้าเป็นสัตว์เลี้ยงของศาลต้าหลี่ เล่ม 2
	Log 	สองนครสิบห้าวัน เล่ม 2

สองนครสิบห้าวัน
	[Documentation]	Thai Test 2
	Log 	ข้าเป็นสัตว์เลี้ยงของศาลต้าหลี่ เล่ม 2
```
<img width="1055" alt="Screen Shot 2021-11-25 at 10 15 04 pm" src="https://user-images.githubusercontent.com/15232871/143439984-e609c9fe-d876-4f87-bb4a-dce6b1f9fb08.png">

(screenshot is MacOS 12.0.1 and python 3.9.1)

I will continue checking the other os's (just need to set up some VM's) now I have a file to test with, hopefully I can get to the cause of this.

Dave.

**Comment by damies13** [comment] 2021-11-25 12:39
I think I know how to fix this, I think I just need to add `encoding="utf8"` whenever I open a file, the key takeaway from the documentation seems to be *"The default encoding is platform dependent"*

https://docs.python.org/3.9/library/functions.html#open

I would still like to be able to reproduce it so I know I've fixed it.

**Comment by castiny** [comment] 2021-11-25 13:42
my python version is 3.8.10 on windows 10 x64

**Comment by castiny** [comment] 2021-11-25 13:46
Thank you and appreciate in endeavour.

**Comment by damies13** [comment] 2021-11-25 13:57
> my python version is 3.8.10 on windows 10 x64

Interesting, this is what I get on Python 3.7.6 on Windows 10, which is not ideal as the Thai text didn't display properly but still better than the error you got.

<img width="797" alt="Screen Shot 2021-11-25 at 11 54 11 pm" src="https://user-images.githubusercontent.com/15232871/143454135-95dddcf6-7940-463d-8c2c-17380fdedc2e.png">

**Comment by damies13** [comment] 2021-11-25 14:31
With Python 3.8.10 on windows 10 I get the same as Python 3.7.6 on Windows 10, if you have a chance can you confirm if you get the same thing as me with LanguageTests.robot, and can you modify LanguageTests.robot to reproduce the error?

Also can you confirm what you did when the error occurred? From the location in the code where the error occurs it looks like you just selected the robot file and the application was generating the test option list.

**Comment by damies13** [comment] 2021-11-29 02:39
@castiny do you know how to checkout a branch and run rfswarm from a branch? 
If so could you check out ["Issue-#97-special-character-(thai-characters)"](https://github.com/damies13/rfswarm/tree/Issue-%2397-special-character-(thai-characters)) and see if this resolves your issue? 

Basically I have made sure on all file reads and writes rfswarm uses UTF-8, I used the test cases above to verify it was displaying correctly. The screen shot below is from that branch.

<img width="796" alt="Screen Shot 2021-11-29 at 12 37 27 pm" src="https://user-images.githubusercontent.com/15232871/143800006-5eb383ec-8270-40eb-9ab1-456f477a9564.png">

**Comment by damies13** [comment] 2021-12-15 00:12
I didn't get confirmation that my example test case could reproduce the issue or and example that could. I believe what I have done will fix the issue but as I was not able to reproduce it I have no way to verify.

I will close this issue so I can push the v0.8.2 bugfix release, if after trying v0.8.2 you are still getting this issue we can reopen this issue and continue investigating.

**Closed by damies13** 2021-12-15 00:12 UTC
Labels: potential bug

**Comment by damies13** [comment] 2021-12-15 00:41
<img width="767" alt="Screen Shot 2021-12-15 at 10 40 52 am" src="https://user-images.githubusercontent.com/15232871/146101746-23f3d6f5-04e6-410b-ad70-c1a44e82cb7c.png">

Running a test that has Thai results

**Comment by castiny** [comment] 2021-12-15 03:16
I will be using v0.8.2 next my project and feedback to you again.

Thank you, you’re amazing!

best regards,
