### ISSUE TITLE
Unable to run the reporter with version 1.1.1 - CLI DOS / windows 10

### ISSUE THREAD

**Issue by orenault** [damies13/rfswarm#147] opened 2023-05-10 10:36 UTC
**Describe the bug**

Unable to run the reporter with version 1.1.1 on a windows 10 Enterprise / cli DOS

**To Reproduce**
Install rf-swarm reporter 1.1.1
run the reporter:  rfswarm-reporter

Got:

Robot Framework Swarm: Reporter
        Version 1.1.1
        Configuration File:  C:\WALK\venvwalk\Lib\site-packages\rfswarm_reporter\RFSwarmReporter.ini
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\WALK\venvwalk\Scripts\rfswarm-reporter.exe\__main__.py", line 4, in <module>
  File "C:\WALK\venvwalk\Lib\site-packages\rfswarm_reporter\rfswarm_reporter.py", line 7724, in <module>
    core = ReporterCore()
           ^^^^^^^^^^^^^^
  File "C:\WALK\venvwalk\Lib\site-packages\rfswarm_reporter\rfswarm_reporter.py", line 2430, in __init__
    base.gui = ReporterGUI()
               ^^^^^^^^^^^^^
  File "C:\WALK\venvwalk\Lib\site-packages\rfswarm_reporter\rfswarm_reporter.py", line 4453, in __init__
    self.BuildUI()
  File "C:\WALK\venvwalk\Lib\site-packages\rfswarm_reporter\rfswarm_reporter.py", line 4668, in BuildUI
    self.ConfigureStyle()
  File "C:\WALK\venvwalk\Lib\site-packages\rfswarm_reporter\rfswarm_reporter.py", line 4789, in ConfigureStyle
    matplotlib.rcParams['font.family'] = fontname
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\WALK\venvwalk\Lib\site-packages\matplotlib\__init__.py", line 735, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key font.family: Expected str or other non-set iterable, but got None


If I downgrade in 1.1.0, the rf-swarm reporter runs well.

**Comment by damies13** [comment] 2023-05-10 23:50
Hi Olivier,

Thanks for the report, I'll spin up a windows VM and start investigating to try and reproduce this.

A couple of questions:
- Do you have an existing template you are using?
  - if yes can you open the template with notepad and let me know what font is on the `font = ` line in the `[Report]` section?
  - Was the template created in V1.1.0 or V1.0.0?

Actually from the error message I suspect this might be the first time you ran Reporter on this machine, but it would be good to confirm that, as it will help trying to reproduce the issue.

Dave.

**Comment by damies13** [comment] 2023-05-12 01:36
Hi Olivier,

As a potential workaround, after running v1.1.0 and letting that create an ini file and template, then try running v1.1.1 and should hopeully start with the template from v1.1.0.

Dave.

**Comment by orenault** [comment] 2023-05-12 07:36
Ok, thanks.
We will try this.
Regards

Olivier

**Comment by damies13** [comment] 2023-05-12 08:33
Hi Olivier,

I managed to reproduce it, thanks for your help.

Dave.

**Comment by damies13** [comment] 2023-05-12 23:20
Good news,

I now have a regression test that reliably reproduces this issue.
The regression test also [confirms that the behavior is the same on all platforms](https://github.com/damies13/rfswarm/actions/runs/4960754522), so that should make the fix easier, no need to do platform specific code :tada:

**Comment by damies13** [comment] 2023-05-14 06:34
Fix merged into Release V1.1.2 branch

**Closed by damies13** 2023-05-14 06:34 UTC
Labels: bug, Reporter, Test

**Comment by orenault** [comment] 2023-05-25 09:17
Hi Dave,

Great thanks.
Seen you've patch it, so test it and the v1.1.2 solves the problem.
Great job!

I think my colleague (Ronny) will contact you.

He is progressing well on a POC with rfswarm, using Docker, Jenkins...
He has an issue with rfswarm-reporter which is stuck on Jenkins.
I guess he will see this directly with you, if you can help us to
understand what happens.

I have a question:
The RF tests are performing well. These tests are only sending GET on an
API and check if the return status is 200.
Each test is about 4s (it include a 2s think time).
I do not know exactly the number of concurrent users run by ronny, but this
produce a lot of RF reports (maybe 100).

What I see, is all the tests may be executed in less than 2 minutes, but
after the end of the execution, it may take more then 4 minutes to produce
all the RF reports.

As far as I know, RF is storing the results in memory, and the results are
dumped in the .xml files at the end of the execution.
Then the RF log files are produced from the xml files.
Is that correct ?

If so, do you have preconizations on the RF log management ?
If rfswarm run a lot of RF tests in //, and the logs are stored in memory
and dumped only at the end of the execution, this may cause a memory leak,
or at least gives some troubles.

I thought that RF will writes the logs at the end of each test suite
execution, or RF threads ending, but it seems to not be the case.
When the last test execution ends at  N, we can see the time of all the log
files are pretty the same, and N+4 minutes.
Is this due to the way that rfswarm start/stop RF ?

Sorry to disturb you with all these questions but this POC with rfswarm is
really important for us.
We are really interested in using it, instead deploying tools like
jmeter/gatling, etc.. (those tools are interesting too, but for more
complicated performance use cases).

Regards
Olivier

**Comment by damies13** [comment] 2023-05-25 10:22
Hi Olivier,

> I think my colleague (Ronny) will contact you.

Is his username on Discord @Anker01 ? If so he already contacted me :+1: 

> What I see, is all the tests may be executed in less than 2 minutes, but
after the end of the execution, it may take more then 4 minutes to produce
all the RF reports.

That's interesting i've never seen it take that long before usually it's under 10 seconds, It shouldn't matter that much each robot runs in a separate thread and process so they don't hold each other up, but I guess it might delay the robot restarting.

> As far as I know, RF is storing the results in memory, and the results are
dumped in the .xml files at the end of the execution.
Then the RF log files are produced from the xml files.
Is that correct ?

I'm not sure how robot works internally, if it's the generation of the html files that's taking the time you could try disabling them

When the agent runs it sets the following command line options to the robot exe:
- -t 
- -d
- --listener
- -o

But you can pass additional options from the manager using [Robot Options](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_manager.md#robot-options), from the command line help for robot you could add `-l NONE -r NONE` and that should stop the html files being generated but the xml will still be created

```
 -l --log file            HTML log file. Can be disabled by giving a special
                          value `NONE`. Default: log.html
                          Examples: `--log mylog.html`, `-l NONE`
 -r --report file         HTML report file. Can be disabled with `NONE`
                          similarly as --log. Default: report.html
```

I guess if necessary I could add an option to the scenario settings to disable the generation of these logs perhaps a checkbox to enable/disable generation for each log, If you'd like that can you raise a feature request for it.

> I thought that RF will writes the logs at the end of each test suite
execution, or RF threads ending, but it seems to not be the case.
When the last test execution ends at  N, we can see the time of all the log
files are pretty the same, and N+4 minutes.
Is this due to the way that rfswarm start/stop RF ?

Yes RF does write the logs at the end of each test suite execution, it writes to the local disk of the agent machine, by default it doesn't get uploaded from the agent to the manager until all the robots finish unless there was test failed, but you can change that setting. 

Now I understand it's taking ~4 min to upload all the logs from the agents to the manager, well my earlier suggestion of not generating the html files will help reduce that. My thinking with the default setting was not to upload the logs during the test to leave as much network bandwidth as possible available from the agent machines to the AUT, I didn't want a scenario where file uploads to the manager affected the test results, someone previously requested to have them uploaded straight away, so now there is an option in [Scenario settings](https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_manager.md#scenario-settings), I left the original behavior (On Error Only) as default, but you can choose how it should behave.

So to put your concern to rest, the RF results are not being stored in memory for the entire test, but on the disk of the agent machine, you just don't see them on the manager till the end of the test. 

> Sorry to disturb you with all these questions but this POC with rfswarm is really important for us.

No problem, I hope your POC goes well :+1: 

Dave.
