### ISSUE TITLE
RFSWARM-Reporter - Does not pick up the start / end time of a test run when using a saved template.

### ISSUE THREAD

**Issue by markro12** [damies13/rfswarm#250] opened 2024-06-12 23:02 UTC
**Describe the bug**
On rfswarm reporter when you have a saved template and you use that to try to generate a report of a new test run. It will not pick up the start and end time of the test run and if you try to generate a report it will be blank since it will not pick up the date/time of the test.

**To Reproduce**
1. Have a saved template of rfswarm reporter
2. Load a new rfswarm run (testrun.db) on the reporter using a previously saved template.
3. Generate a word/xls report
4. Observe the report is blank, check that the date/time on the rfswarm reporter is the same as when you initially saved the template.

**Expected behavior**
Its expected that when you load a new testrun.db to try to generate a report, it will pick up the date/time on when the test was executed.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Windows
- BrowserChrome
- Version 126
- office 365
- rfswarm reporter version 1.3.0

**Additional context**

**Comment by damies13** [comment] 2024-06-13 00:08
@markro12 Thanks for the bug report 👍 

Can you confirm: 
- The first step "Have a saved template of rfswarm reporter", was this template created with an earlier version of rfswarm reporter? if so which version?
- Are you using the the `--nogui` option when generating your report? have you tried it without the `--nogui` option (I expect you'll get the same result but it'll be useful to know if that works)

Potentially a workaround might be to create a .report file in the same directory as the db file with the start and end time in it, not sure if that'll work but it's worth a try while I work on a fix.

I'll start investigating this later today.

**Comment by damies13** [comment] 2024-06-14 10:48
Hi @markro12,

After a fair bit of trying things I'm not able to reproduce your issue with ether 1.3.0 or 1.3.1

What I did find is with 1.3.0 the display of the start and end time as well as the date were displayed incorrectly when running with the `--nogui` option on the command line, i.e. my test results folder from the 5th of June from 21:00 to 21:31 showed today's date (14 June)  and the time I generated the report as the start and end time. however when I run the same way with 1.3.1 I get the correct date and times. I'm not really sure why, there were no fixes in 1.3.1 for reporter.

Can you try 1.3.1 and see of that fixes the issue for you?

**Comment by damies13** [comment] 2024-06-27 11:06
Hi @markro12, 

Good news, with help from @ArekKuczynski we've managed to reproduce this issue.

We also have a partial workaround, open the template file with a text editor and change the `starttime` and `endtime` to `0`, then the template will generate a report with data, but it won't be constrained like it was in your original report

```
starttime = 0
endtime = 0
```

I will work on a better fix for this issue.

**Comment by damies13** [comment] 2024-07-07 02:05
Merged into release V1.3.2

**Closed by damies13** 2024-07-07 02:05 UTC
Labels: bug, Reporter
